"""Mersenne Twister (MT19937) state untempering and output predictor.

Reverses MT19937 tempering operations to recover the internal 624-word state array
and predict all future or previous outputs generated by Python's `random` module.
"""

from __future__ import annotations

import random


def untemper(y: int) -> int:
    """Inverts the MT19937 tempering transformations to recover the internal generator word."""
    # 1. Invert: y = y ^ (y >> 18)
    y = y ^ (y >> 18)

    # 2. Invert: y = y ^ ((y << 15) & 0xEFC60000)
    y = y ^ ((y << 15) & 0xEFC60000)

    # 3. Invert: y = y ^ ((y << 7) & 0x9D2C5680)
    # Reconstructed 7 bits at a time
    mask = 0x9D2C5680
    b = y & 0x7F
    for shift in (7, 14, 21, 28):
        b |= (y ^ ((b << 7) & mask)) & ((0x7F << shift) & 0xFFFFFFFF)
    y = b

    # 4. Invert: y = y ^ (y >> 11)
    # Reconstructed 11 bits at a time
    a = y & 0xFFE00000
    a |= (y ^ (a >> 11)) & 0x001FFC00
    a |= (y ^ (a >> 11)) & 0x000003FF
    return a


def clone_mt19937_generator(outputs_624: list[int]) -> random.Random:
    """Clones a Python random.Random instance from 624 consecutive 32-bit outputs."""
    if len(outputs_624) < 624:
        raise ValueError(f"Need at least 624 outputs to reconstruct MT19937, got {len(outputs_624)}")

    state = [untemper(x) for x in outputs_624[:624]]
    # Python random tuple state: (3, tuple(state + [624]), None)
    rng = random.Random()
    rng.setstate((3, tuple(state + [624]), None))
    return rng
