from __future__ import annotations

# A realistic distribution for testing substitution solver
# Log probabilities based on large English corpus
QUADGRAMS: dict[str, float] = {
    "TION": -2.5,
    "NTHE": -2.6,
    "THER": -2.7,
    "THAT": -2.8,
    "OFTH": -2.8,
    "FTHE": -2.9,
    "THES": -3.0,
    "WITH": -3.1,
    "INTH": -3.1,
    "ATIO": -3.2,
    "OURS": -3.2,
    "MENT": -3.3,
    "HERE": -3.4,
    "FROM": -3.4,
    "THIS": -3.5,
    "HAVE": -3.5,
    "THEY": -3.6,
    "WERE": -3.6,
    "WHIC": -3.7,
    "HICH": -3.7,
    "TTHE": -3.8,
    "THEM": -3.8,
    "ANDT": -3.9,
    "OTHE": -3.9,
    "WHAT": -4.0,
    "SOME": -4.0,
    "TIME": -4.1,
    "ABOU": -4.1,
    "BOUT": -4.2,
    "OULD": -4.2,
    "WOUL": -4.3,
    "COUL": -4.3,
    "SHOU": -4.4,
    "HOUL": -4.4,
    "THEI": -4.5,
    "HEIR": -4.5,
    "THIN": -4.6,
    "HING": -4.6,
    # Adding a few more to make it a bit larger
    "ANTR": -4.7,
    "ESTS": -4.8,
    "TEST": -4.8,
    "STHE": -4.9,
    "EDTH": -4.9,
    "NGTH": -5.0,
    "RTHE": -5.0,
    "OFT": -5.1,
    "WILL": -5.1,
    "MORE": -5.2,
    "THEN": -5.2,
    "NOWT": -5.3,
    "BEEN": -5.3,
    "MUCH": -5.4,
    "YOUR": -5.4,
    "WHEN": -5.5,
}
FLOOR = -10.0
