"""Control Flow Flattening (CFF) and OLLVM Dispatcher Analysis.

Detects flattened switch/while dispatcher loops commonly generated by
obfuscators like OLLVM and Tigress, extracting state variable transitions
to reconstruct the original linear basic block flow.
"""

from __future__ import annotations

from typing import Any

from ichnos.reverse.cfg import BasicBlock, build_cfg
from ichnos.reverse.disasm import disassemble


def detect_control_flow_flattening(
    code: bytes,
    base_addr: int = 0x400000,
    arch: str = "x86_64",
) -> dict[str, Any]:
    """Analyzes code to detect control-flow flattening obfuscation.

    Args:
        code: Executable machine code.
        base_addr: Starting virtual address.
        arch: Architecture ('x86_64' or 'x86').

    Returns:
        Dict with: 'flattened': bool, 'dispatcher_addr': int | None,
        'state_blocks': list, 'unflattened_order': list.
    """
    insns = disassemble(code, arch=arch, base_addr=base_addr)
    blocks = build_cfg(insns)

    if not blocks:
        return {"flattened": False, "dispatcher_addr": None, "state_blocks": []}

    # In CFF, the central dispatcher block has:
    # 1. High in-degree (many blocks jump back to it)
    # 2. High out-degree (branches to many case handlers)
    in_degree: dict[int, int] = {b.id: 0 for b in blocks}

    for b in blocks:
        for succ_id in b.successors:
            if succ_id in in_degree:
                in_degree[succ_id] += 1

    # Find candidate dispatcher
    candidate_dispatcher: BasicBlock | None = None
    max_in = 0
    for b in blocks:
        indeg = in_degree[b.id]
        # Dispatchers typically have >= 3 in-edges in non-trivial functions
        if indeg >= 3 and indeg > max_in:
            max_in = indeg
            candidate_dispatcher = b

    if not candidate_dispatcher:
        return {
            "flattened": False,
            "dispatcher_addr": None,
            "state_blocks": [],
            "reason": "No high-indegree central dispatcher block detected",
        }

    # Identify case handler blocks (blocks whose successor is the dispatcher)
    disp_id = candidate_dispatcher.id
    disp_addr = candidate_dispatcher.start_addr
    case_blocks: list[dict[str, Any]] = []

    for b in blocks:
        if b.id != disp_id and disp_id in b.successors:
            # Check for constant state variable assignments in this block
            # (e.g. mov dword ptr [rbp-4], 0x1234 or mov eax, 0x1234)
            state_val = None
            for insn in b.instructions:
                if insn.mnemonic.lower() == "mov" and insn.op_str:
                    ops = [o.strip() for o in insn.op_str.split(",")]
                    if len(ops) == 2 and (ops[1].isdigit() or ops[1].startswith("0x")):
                        try:
                            state_val = int(ops[1], 16 if ops[1].startswith("0x") else 10)
                        except Exception:
                            pass

            case_blocks.append({
                "block_addr": b.start_addr,
                "size": b.size(),
                "insn_count": len(b.instructions),
                "next_state": state_val,
            })

    return {
        "flattened": True,
        "dispatcher_addr": disp_addr,
        "back_edges_count": max_in,
        "case_blocks_count": len(case_blocks),
        "case_blocks": case_blocks,
        "technique": "OLLVM / Tigress State-Variable Dispatcher Loop",
    }
