"""Tests for PRNG and Stream cryptanalysis (LCG, MT19937, LFSR Berlekamp-Massey)."""

from __future__ import annotations

import random

from ichnos.crypto.prng.lcg import compose_lcg, crack_time_seeded_lcg
from ichnos.crypto.prng.mersenne import clone_mt19937_generator
from ichnos.crypto.stream.lfsr import berlekamp_massey, lfsr_recover_and_predict
from ichnos.crypto.symmetric.aes import encrypt_ecb


def test_compose_lcg():
    a = 16843009
    b = 826366247
    m = 2**32
    n = 100

    # Test closed-form matrix power vs iterative loop
    s = 12345
    s_loop = s
    for _ in range(n):
        s_loop = (a * s_loop + b) % m

    A, B = compose_lcg(a, b, m, n)
    s_matrix = (A * s + B) % m
    assert s_matrix == s_loop


def test_crack_time_seeded_lcg():
    import hashlib

    a = 16843009
    b = 826366247
    m = 2**32
    iterations = 50

    target_t = 1700000000
    A, B = compose_lcg(a, b, m, iterations)
    winning_seed = (A * (target_t % m) + B) % m
    key = hashlib.sha256(str(winning_seed).encode()).digest()

    flag = b"FLAG{test_lcg_crack_works!}"
    pad_len = 16 - (len(flag) % 16)
    padded = flag + bytes([pad_len] * pad_len)
    ct = encrypt_ecb(key, padded)

    # Search with window centered around target_t
    res = crack_time_seeded_lcg(ct, a, b, m, iterations, ref_time=target_t, search_window=500)
    assert res is not None
    t, seed, k, flag_str = res
    assert t == target_t
    assert seed == winning_seed
    assert "FLAG{test_lcg_crack_works!}" in flag_str


def test_mt19937_untemper():
    rng = random.Random(42)
    # Generate 624 outputs
    outputs = [rng.getrandbits(32) for _ in range(624)]

    # Clone state
    cloned = clone_mt19937_generator(outputs)

    # Verify next 100 outputs match exactly
    for _ in range(100):
        assert rng.getrandbits(32) == cloned.getrandbits(32)


def test_berlekamp_massey():
    # Sequence generated by x^4 + x + 1 (period 15)
    # Taps at 4 and 1
    state = [1, 0, 0, 0]
    seq = []
    for _ in range(20):
        seq.append(state[0])
        feedback = state[0] ^ state[3]
        state = state[1:] + [feedback]

    poly = berlekamp_massey(seq)
    # Degree should be 4
    assert len(poly) - 1 == 4

    # Test prediction
    predicted = lfsr_recover_and_predict(seq[:10], num_future_bits=10)
    assert predicted == seq[10:20]
